services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: masterkey
    networks:
      api:
        ipv4_address: 192.168.92.9
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: "service_healthy"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    networks:
      api:
        ipv4_address: 192.168.92.10
networks:
  api:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"