FROM ubuntu:latest

RUN apt-get update && apt-get install -y openjdk-11-jdk
COPY ./target/schneiderstream-0.0.1-SNAPSHOT.jar /app/schneiderstream-0.0.1-SNAPSHOT.jar
WORKDIR /app/schneiderstream-0.0.1-SNAPSHOT.jar
RUN echo "Starting jar file"
CMD ["java", "-jar", "schneiderstream-0.0.1-SNAPSHOT.jar"]