services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_DATABASE: SCHNEIDERSTREAM
    ports:
      - 3306:3306
    networks:
      rest:
        ipv4_address: 192.168.92.9
#   web:
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     build: .
#     networks:
#       rest:
#         ipv4_address: 192.168.92.10
networks:
  rest:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
