services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
    networks:
      rest:
        ipv4_address: 192.168.92.9
  web:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "9090:9090"
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile.dev
    networks:
      rest:
        ipv4_address: 192.168.92.10
networks:
  rest:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
