CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    idade INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    title ENUM('ESPECIALISTA_EM_ENERGIA_VERDE', 'CICLISTA_CONSCIENTE', 'MESTRE_DA_RECICLAGEM'),
    score INT DEFAULT 0,
    foto TEXT,
    descricao TEXT,
    cargo VARCHAR(255)
);
